### ISSUE TITLE
LC-QuAD  dataset

### ISSUE THREAD

**Issue by xqx1568** [WDAqua/Frankenstein#5]
Can you give me the dataset from LC-QuAD in your experiment ,the 3,252 questions which SPARQL queries can returned an answer.
I want use this to do another experiment about SPARQL.
My Email:mg1833080@smail.nju.edu.cn
Looking forward to your reply.

**Comment by kulsingh** [comment]
Sure, I will do it. Will send you the same soon.

**Comment by D063520** [comment]
Hi,

here is the link of the dataset:

http://lc-quad.sda.tech

Salut
D063520

**Comment by xqx1568** [comment]
Thank  you for your reply.I find the dataset  in your another experiment github.Thank you.
